import { useEffect, useMemo, useState } from 'react';
import type { CSSProperties } from 'react';
import { Icon } from '@iconify/react';
import { Search, SlidersHorizontal, X, Heart, Copy, Download, RotateCw, FlipHorizontal, FlipVertical, Check, ExternalLink, Code2, Grid3X3, Moon, Sun, ChevronDown, LoaderCircle, Minus, Plus } from 'lucide-react';
import { getCollection, getCollections, getIconData, searchIcons } from './api';
import type { CollectionInfo, Collections, IconData, IconRef } from './types';

const parse=(id:string):IconRef=>{const [prefix,...rest]=id.replace(/^@?/, '').split(':');return {prefix,name:rest.join(':')}};
const idOf=(i:IconRef)=>`${i.prefix}:${i.name}`;
const copy=(v:string)=>navigator.clipboard.writeText(v);
const download=(content:string,name:string,type='image/svg+xml')=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)};
const expandHex=(color:string)=>color.length===4?`#${color.slice(1).split('').map(char=>char+char).join('')}`:color.slice(0,7);
const escapeRegExp=(value:string)=>value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
const PAGE_SIZE=96;

export default function App(){
 const [collections,setCollections]=useState<Collections>({}); const [categoryIndex,setCategoryIndex]=useState<Record<string,string[]>>({}); const [query,setQuery]=useState(''); const [debounced,setDebounced]=useState(''); const [prefix,setPrefix]=useState(''); const [category,setCategory]=useState('All categories'); const [categoryQuery,setCategoryQuery]=useState(''); const [icons,setIcons]=useState<string[]>([]); const [totalIcons,setTotalIcons]=useState(0); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [selected,setSelected]=useState<IconRef|null>(null); const [dark,setDark]=useState(()=>localStorage.theme==='dark'); const [gridSize,setGridSize]=useState(()=>Number(localStorage.getItem('icon-grid-size'))||120); const [favorites,setFavorites]=useState<string[]>(()=>JSON.parse(localStorage.getItem('icon-favorites')||'[]')); const [showFavs,setShowFavs]=useState(false); const [page,setPage]=useState(0); const [hasMore,setHasMore]=useState(false);
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.theme=dark?'dark':'light'},[dark]);
 useEffect(()=>{localStorage.setItem('icon-grid-size',String(gridSize))},[gridSize]);
 useEffect(()=>{getCollections().then(setCollections).catch(e=>setError(e.message))},[]);
 useEffect(()=>{fetch('/category-index.json').then(r=>{if(!r.ok)throw new Error('Category index could not be loaded');return r.json()}).then(setCategoryIndex).catch(e=>setError(e.message))},[]);
 useEffect(()=>{const t=setTimeout(()=>setDebounced(query.trim()),300);return()=>clearTimeout(t)},[query]);
 useEffect(()=>{setPage(0)},[debounced,prefix,category,showFavs]);
 useEffect(()=>{const lastPage=Math.max(0,Math.ceil(totalIcons/PAGE_SIZE)-1);if(page>lastPage)setPage(lastPage)},[page,totalIcons]);
 useEffect(()=>{if(showFavs){setTotalIcons(favorites.length);setIcons(favorites.slice(page*PAGE_SIZE,(page+1)*PAGE_SIZE));setHasMore(favorites.length>(page+1)*PAGE_SIZE);setLoading(false);return} const c=new AbortController(); setLoading(true);setError(''); const chosen=prefix||''; if(category!=='All categories'){let all=categoryIndex[category]||[];if(chosen)all=all.filter(id=>id.startsWith(`${chosen}:`));if(debounced){const term=debounced.toLowerCase();all=all.filter(id=>id.toLowerCase().includes(term))}setTotalIcons(all.length);setIcons(all.slice(page*PAGE_SIZE,(page+1)*PAGE_SIZE));setHasMore(all.length>(page+1)*PAGE_SIZE);setLoading(false)} else if(debounced){searchIcons(debounced,chosen,PAGE_SIZE,page*PAGE_SIZE,c.signal).then(r=>{setTotalIcons(r.total);setIcons(r.icons);setHasMore(r.start+r.icons.length<r.total)}).catch(e=>e.name!=='AbortError'&&setError(e.message)).finally(()=>setLoading(false));} else {const target=chosen||'lucide';getCollection(target,c.signal).then(r=>{const all=[...new Set([...(r.uncategorized||[]),...Object.values(r.categories||{}).flat()])];setTotalIcons(all.length);setIcons(all.slice(page*PAGE_SIZE,(page+1)*PAGE_SIZE).map(n=>`${target}:${n}`));setHasMore(all.length>(page+1)*PAGE_SIZE)}).catch(e=>e.name!=='AbortError'&&setError(e.message)).finally(()=>setLoading(false));} return()=>c.abort()},[debounced,prefix,category,categoryIndex,page,showFavs,favorites]);
 const categories=useMemo(()=>['All categories',...Object.keys(categoryIndex)],[categoryIndex]);
 const visibleCategories=useMemo(()=>categories.filter(c=>c.toLowerCase().includes(categoryQuery.toLowerCase())),[categories,categoryQuery]);
 const filteredCollections=useMemo(()=>Object.entries(collections),[collections]);
 const toggleFav=(id:string)=>setFavorites(v=>{const n=v.includes(id)?v.filter(x=>x!==id):[...v,id];localStorage.setItem('icon-favorites',JSON.stringify(n));return n});
 return <div className="app">
  <header><div className="brand"><span className="logo"><Grid3X3 size={19}/></span><span>Glyph</span><b>Studio</b></div><div className="search"><Search size={19}/><input aria-label="Search icons" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search 300,000+ icons…"/><kbd>⌘ K</kbd></div><nav><button className={showFavs?'active':''} onClick={()=>setShowFavs(!showFavs)}><Heart size={18} fill={showFavs?'currentColor':'none'}/> <span>Saved</span></button><a href="https://iconify.design/docs/" target="_blank">Docs <ExternalLink size={14}/></a><button className="theme-toggle" aria-label="Toggle theme" onClick={()=>setDark(!dark)}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button></nav></header>
  <main>
   <aside><div className="aside-title">Categories <span>{Object.keys(categoryIndex).length}</span></div><div className="category-search"><Search size={14}/><input aria-label="Filter categories" placeholder="Filter categories…" value={categoryQuery} onChange={e=>setCategoryQuery(e.target.value)}/>{categoryQuery&&<button aria-label="Clear category filter" onClick={()=>setCategoryQuery('')}><X size={13}/></button>}</div><div className="category-list">{visibleCategories.map(c=><button className={category===c?'side-active':''} key={c} onClick={()=>{setCategory(c);setShowFavs(false)}} title={c}>{c}<span>{c==='All categories'?Object.values(categoryIndex).reduce((n,v)=>n+v.length,0).toLocaleString():(categoryIndex[c]?.length||0).toLocaleString()}</span></button>)}</div></aside>
   <section className="content"><div className="toolbar"><div><h1>{showFavs?'Saved icons':category!=='All categories'?category:debounced?`Results for “${debounced}”`:prefix?collections[prefix]?.name||prefix:'Explore icons'}</h1><p>{showFavs?`${favorites.length} icons saved locally`:category!=='All categories'?`${(categoryIndex[category]?.length||0).toLocaleString()} categorized icons${prefix?` in ${collections[prefix]?.name||prefix}`:''}`:prefix?`${collections[prefix]?.total?.toLocaleString()||''} icons · ${collections[prefix]?.license?.title||'Open source'}`:'Browse beautiful open-source icon collections'}</p></div><div className="filters"><label><SlidersHorizontal size={16}/><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select><ChevronDown size={14}/></label><label><select value={prefix} onChange={e=>{setPrefix(e.target.value);setShowFavs(false)}}><option value="">All sets</option>{filteredCollections.sort((a,b)=>a[1].name.localeCompare(b[1].name)).map(([k,v])=><option value={k} key={k}>{v.name}</option>)}</select><ChevronDown size={14}/></label><div className="view-size" title="Change icon view size"><button aria-label="Decrease icon size" disabled={gridSize<=88} onClick={()=>setGridSize(size=>Math.max(88,size-16))}><Minus size={14}/></button><input aria-label="Icon view size" type="range" min="88" max="184" step="16" value={gridSize} onChange={e=>setGridSize(Number(e.target.value))}/><button aria-label="Increase icon size" disabled={gridSize>=184} onClick={()=>setGridSize(size=>Math.min(184,size+16))}><Plus size={14}/></button></div></div></div>
    {error&&<div className="error">{error} <button onClick={()=>location.reload()}>Retry</button></div>}
    {loading?<div className="loading"><LoaderCircle className="spin"/>Loading icons…</div>:icons.length?<div className="grid" style={{'--grid-size':`${gridSize}px`,'--icon-size':`${Math.round(gridSize*.32)}px`} as CSSProperties}>{icons.map(raw=>{const i=parse(raw);const id=idOf(i);return <button className="card" key={id} onClick={()=>setSelected(i)}><span className="fav" onClick={e=>{e.stopPropagation();toggleFav(id)}}><Heart size={15} fill={favorites.includes(id)?'currentColor':'none'}/></span><Icon icon={id} width="var(--icon-size)" height="var(--icon-size)"/><span className="icon-name">{i.name}</span><small>{i.prefix}</small></button>})}</div>:<div className="empty"><Search size={32}/><h2>No icons found</h2><p>Try another keyword or collection.</p></div>}
    {!loading&&icons.length>0&&<Pagination page={page} total={totalIcons} hasMore={hasMore} onPageChange={setPage}/>}
   </section>
  </main>
  {selected&&<Editor icon={selected} info={collections[selected.prefix]} saved={favorites.includes(idOf(selected))} onSave={()=>toggleFav(idOf(selected))} onClose={()=>setSelected(null)}/>} 
 </div>
}

function Pagination({page,total,hasMore,onPageChange}:{page:number;total:number;hasMore:boolean;onPageChange:(page:number)=>void}){
 const totalPages=Math.max(1,Math.ceil(total/PAGE_SIZE)); const first=page*PAGE_SIZE+1; const last=Math.min((page+1)*PAGE_SIZE,total);
 return <div className="pager">
  <span className="pager-summary">Showing {first.toLocaleString()}–{last.toLocaleString()} of {total.toLocaleString()} icons</span>
  <div className="pager-controls">
   <button disabled={page===0} onClick={()=>onPageChange(page-1)}>Previous</button>
   <label>Page <input aria-label="Page number" type="number" min="1" max={totalPages} value={page+1} onChange={e=>{const value=Number(e.target.value);if(value>=1&&value<=totalPages)onPageChange(value-1)}}/> of {totalPages.toLocaleString()}</label>
   <button disabled={!hasMore} onClick={()=>onPageChange(page+1)}>Next</button>
  </div>
 </div>
}

function Editor({icon,info,saved,onSave,onClose}:{icon:IconRef;info?:CollectionInfo;saved:boolean;onSave:()=>void;onClose:()=>void}){
 const [data,setData]=useState<IconData|null>(null);const [size,setSize]=useState(128);const [colorMode,setColorMode]=useState<'solid'|'gradient'>('solid');const [color,setColor]=useState('#15171a');const [gradientEnd,setGradientEnd]=useState('#6656e8');const [gradientAngle,setGradientAngle]=useState(135);const [paletteEdits,setPaletteEdits]=useState<Record<string,string>>({});const [rotation,setRotation]=useState(0);const [hFlip,setHFlip]=useState(false);const [vFlip,setVFlip]=useState(false);const [tab,setTab]=useState<'react'|'svg'|'css'|'json'>('react');const [toast,setToast]=useState('');
 useEffect(()=>{getIconData(icon.prefix,icon.name).then(setData)},[icon]);
 const body=data?.body||''; const palette=useMemo(()=>[...new Set(body.match(/#[0-9a-fA-F]{3,8}\b/g)||[])],[body]);
 useEffect(()=>{setPaletteEdits(Object.fromEntries(palette.map(value=>[value,expandHex(value)])))},[body]);
 const isMulticolor=palette.length>1; const paletteBody=palette.reduce((content,original)=>content.replace(new RegExp(escapeRegExp(original),'gi'),paletteEdits[original]||original),body);
 const id=idOf(icon); const transform=`${hFlip?'scale(-1,1) ':''}${vFlip?'scale(1,-1) ':''}rotate(${rotation}deg)`; const w=data?.width||16,h=data?.height||16,left=data?.left||0,top=data?.top||0; const viewBox=`${left} ${top} ${w} ${h}`; const gradient=`linear-gradient(${gradientAngle}deg, ${color}, ${gradientEnd})`; const gradientBody=paletteBody.replaceAll('currentColor','url(#icon-gradient)'); const svg=!isMulticolor&&colorMode==='gradient'?`<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="${viewBox}" style="transform:${transform}"><defs><linearGradient id="icon-gradient" gradientTransform="rotate(${gradientAngle} .5 .5)"><stop stop-color="${color}"/><stop offset="1" stop-color="${gradientEnd}"/></linearGradient></defs>${gradientBody}</svg>`:`<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="${viewBox}" style="color:${color};transform:${transform}">${paletteBody}</svg>`; const reactCode=isMulticolor?`<span dangerouslySetInnerHTML={{ __html: ${JSON.stringify(svg)} }} />`:colorMode==='gradient'?`<span style={{\n  display: 'inline-block',\n  width: ${size},\n  height: ${size},\n  background: '${gradient}',\n  mask: \"url('https://api.iconify.design/${icon.prefix}/${icon.name}.svg') center / contain no-repeat\",\n  WebkitMask: \"url('https://api.iconify.design/${icon.prefix}/${icon.name}.svg') center / contain no-repeat\",\n  transform: '${transform}'\n}} />`:`import { Icon } from '@iconify/react';\n\n<Icon\n  icon="${id}"\n  width={${size}}\n  color="${color}"\n  rotate={${rotation/90}}\n  hFlip={${hFlip}}\n  vFlip={${vFlip}}\n/>`; const code={react:reactCode,svg,css:isMulticolor?`/* Multi-color icons preserve their customized fills in the SVG. */\n.icon-${icon.name} { width: ${size}px; height: ${size}px; transform: ${transform}; }`:`.icon-${icon.name} {\n  display: inline-block;\n  width: ${size}px;\n  height: ${size}px;\n  background: ${colorMode==='gradient'?gradient:color};\n  mask: url('https://api.iconify.design/${icon.prefix}/${icon.name}.svg') no-repeat center / contain;\n  -webkit-mask: url('https://api.iconify.design/${icon.prefix}/${icon.name}.svg') no-repeat center / contain;\n  transform: ${transform};\n}`,json:JSON.stringify({prefix:icon.prefix,name:icon.name,customizations:{size,colorMode,color,gradientEnd,gradientAngle,palette:paletteEdits,rotation,hFlip,vFlip},...data},null,2)}[tab];
 const copied=()=>{copy(code);setToast('Copied');setTimeout(()=>setToast(''),1200)};
 return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="drawer"><div className="drawer-head"><div><small>{info?.name||icon.prefix}</small><h2>{icon.name}</h2></div><div><button onClick={onSave}><Heart size={18} fill={saved?'currentColor':'none'}/></button><button onClick={onClose}><X size={20}/></button></div></div><div className="editor-body">
  <div className="preview"><div className="preview-stage">{isMulticolor?<svg width={size} height={size} viewBox={viewBox} style={{color,transform}} dangerouslySetInnerHTML={{__html:paletteBody}}/>:colorMode==='gradient'?<span className="gradient-icon" style={{width:size,height:size,background:gradient,mask:`url('https://api.iconify.design/${icon.prefix}/${icon.name}.svg') center / contain no-repeat`,WebkitMask:`url('https://api.iconify.design/${icon.prefix}/${icon.name}.svg') center / contain no-repeat`,transform}}/>:<Icon icon={id} width={size} height={size} color={color} rotate={rotation/90} hFlip={hFlip} vFlip={vFlip}/>}</div><span>{size} × {size}px</span></div>
  <div className="controls"><div className="control-head"><h3>Customize</h3><button onClick={()=>{setSize(128);setColorMode('solid');setColor('#15171a');setGradientEnd('#6656e8');setGradientAngle(135);setPaletteEdits(Object.fromEntries(palette.map(value=>[value,expandHex(value)])));setRotation(0);setHFlip(false);setVFlip(false)}}>Reset</button></div><div className="control-block"><span className="control-label">Size <b>{size}px</b></span><div className="size-presets">{[16,24,32,48,64,128].map(value=><button className={size===value?'selected':''} onClick={()=>setSize(value)} key={value}>{value}</button>)}</div><input className="size-range" aria-label="Custom icon size" type="range" min="16" max="256" value={size} onChange={e=>setSize(+e.target.value)}/></div>{isMulticolor?<div className="control-block"><span className="control-label">Icon palette <b>{palette.length} colors</b></span><div className="palette-controls">{palette.map((original,index)=><label key={original}><span><i style={{background:paletteEdits[original]||original}}/>Color {index+1}<small>{original}</small></span><span className="color"><input aria-label={`Color ${index+1}`} type="color" value={paletteEdits[original]||expandHex(original)} onChange={e=>setPaletteEdits(current=>({...current,[original]:e.target.value}))}/><input value={paletteEdits[original]||original} onChange={e=>setPaletteEdits(current=>({...current,[original]:e.target.value}))}/></span></label>)}</div></div>:<><div className="control-block"><span className="control-label">Color style</span><div className="mode-toggle"><button className={colorMode==='solid'?'selected':''} onClick={()=>setColorMode('solid')}>Solid</button><button className={colorMode==='gradient'?'selected':''} onClick={()=>setColorMode('gradient')}>Gradient</button></div></div><label>{colorMode==='gradient'?'Start color':'Color'} <span className="color"><input type="color" value={color} onChange={e=>setColor(e.target.value)}/><input value={color} onChange={e=>setColor(e.target.value)}/></span></label>{colorMode==='gradient'&&<><label>End color <span className="color"><input type="color" value={gradientEnd} onChange={e=>setGradientEnd(e.target.value)}/><input value={gradientEnd} onChange={e=>setGradientEnd(e.target.value)}/></span></label><label>Gradient angle <b>{gradientAngle}°</b><input type="range" min="0" max="360" step="15" value={gradientAngle} onChange={e=>setGradientAngle(+e.target.value)}/></label></>}</>}<label>Transform <span className="button-row"><button className={rotation?'selected':''} onClick={()=>setRotation((rotation+90)%360)}><RotateCw size={16}/> {rotation}°</button><button className={hFlip?'selected':''} onClick={()=>setHFlip(!hFlip)}><FlipHorizontal size={16}/></button><button className={vFlip?'selected':''} onClick={()=>setVFlip(!vFlip)}><FlipVertical size={16}/></button></span></label></div>
  <div className="code"><div className="tabs">{(['react','svg','css','json'] as const).map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t.toUpperCase()}</button>)}</div><pre>{code}</pre><button className="copy" onClick={copied}>{toast?<><Check size={15}/>{toast}</>:<><Copy size={15}/>Copy</>}</button></div>
  <div className="meta"><h3>About this icon</h3><dl><div><dt>Collection</dt><dd>{info?.name||icon.prefix}</dd></div><div><dt>License</dt><dd>{info?.license?.url?<a href={info.license.url} target="_blank">{info.license.title}</a>:info?.license?.title||'See collection'}</dd></div><div><dt>Dimensions</dt><dd>{w} × {h}</dd></div><div><dt>Palette</dt><dd>{info?.palette?'Multicolor':'Monotone'}</dd></div></dl></div>
 </div><div className="drawer-foot"><button className="secondary" onClick={()=>download(svg,`${icon.name}.svg`)}><Download size={17}/> Download SVG</button><button className="primary" onClick={copied}><Code2 size={17}/> Copy {tab.toUpperCase()}</button></div></div></div>
}
